lib/hq_tw/web/router.ex
defmodule HqTw.Web.Router do
  use HqTw.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HqTw.Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  scope "/samples", HqTw.Web do
    pipe_through :browser

    get "/login", SamplePageController, :login
    get "/dashboard", SamplePageController, :dashboard
    get "/client", SamplePageController, :client
  end
  # Other scopes may use custom stacks.
  # scope "/api", HqTw.Web do
  #   pipe_through :api
  # end
end

lib/hq_tw/web/controllers/page_controller.ex
defmodule HqTw.Web.PageController do
  use HqTw.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/hq_tw/web/controllers/sample_page_controller.ex
defmodule HqTw.Web.SamplePageController do
  use HqTw.Web, :controller

  plug :put_layout, false

  def login(conn, _param) do
    render(conn)
  end

  def dashboard(conn, _param) do
    render(conn)
  end

  def client(conn, _param) do
    render(conn)
  end
end

lib/hq_tw/web/views/error_view.ex
defmodule HqTw.Web.ErrorView do
  use HqTw.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/hq_tw/web/views/layout_view.ex
defmodule HqTw.Web.LayoutView do
  use HqTw.Web, :view
end

lib/hq_tw/web/views/page_view.ex
defmodule HqTw.Web.PageView do
  use HqTw.Web, :view
end

lib/hq_tw/web/views/sample_page_view.ex
defmodule HqTw.Web.SamplePageView do
  use HqTw.Web, :view
end

lib/hq_tw/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello HqTw!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/hq_tw/web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

lib/hq_tw/web/templates/sample_page/client.html.eex
<!doctype html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Welcome to Heqet</title>
      <style type="text/css">
        @charset "UTF-8";
        @import url('https://fonts.googleapis.com/css?family=Hind+Siliguri|Roboto+Slab');

        body{
          font-family: 'Hind Siliguri', serif;
          font-size:1em;
          color:#333;
          margin:0 auto;
          width:90%;
          }
        li{
          list-style:none;
          display:block;
          display:inline;

          }
        a{
          color: inherit;
          text-decoration:none;
          }
        /*font*/
        .hello{
          font-family: 'Hind Siliguri', sans-serif;
          color:#333;
          font-size:1.55em;
          font-weight:bold;
          letter-spacing:0em;
          margin:1.5em 0 2em 0em;
          }
        .info{
          font-size:1.5em;
          }
        /*color*/
          .pregnancy{background-color:#b0ccd9;
                }
            .due{background-color:#67a8bd;
                  }
              .pCare{background-color:#e1c1c3;
                    }
                .closed{background-color:#b1b3b6;
                      }

                /*memberdb*/

                #logo img{
                  float:left;
                  margin:1.5em;
                  width:4.1em;
                }
                #header{
                  width:100%;
                  float:left;
                  margin-bottom:1em;

                  }
                #header li {
                  text-align:center;
                  float:left;
                  margin-bottom:1em;
                  width:31.5%;
                  margin: 0.5%;
                  }

                .viewAll{
                  color:#67a8bd;
                  font-weight:normal;
                  border:1px solid #67a8bd;
                  border-radius: 40px;
                    }

                .add{
                  border-radius: 40px;
                  color:#FFF;
                  background-color:#67a8bd;
                  }
                .tool{
                  border-radius: 40px;
                  color:#b1b3b6;
                  border:1px solid #b1b3b6;
                  }
                #search{
                  text-align:center;
                  clear:left;
                  float:left;
                  width:100%;
                  border:1px solid #b1b3b6;;
                  color:#b1b3b6;
                  margin-bottom:1em;
                  border-radius: 40px;
                  }
                #clientz{
                  width:100%;
                  margin-bottom:1em;
                  }
                #clientz li{
                  float:left;
                  color:#fff;
                  width:30%;
                  height:12em;
                  margin:0.5%;
                  padding: 0 0 0 2%;
                  }


                #subNav{
                  font-family:"Hind Siliguri", sans-serif;
                  margin:1em 0em 0em 1em;
                  width:100%;
                  float:left;
                  }

                #subNav li{
                    color:#b1b3b6;
                    float:left;
                    width:31.5%;
                    border-right:1px solid #b1b3b6;
                    margin: 0.3%;
                    font-size:14px;
                    text-align:center;
                   }
                #subNav a{
                    color:#b1b3b6;
                   }
                #subNav a:hover{
                       color:#67a8bd;
                       text-decoration:underline;
                       }

                #footer{

                  color:#b1b3b6;
                  text-align:center;
                  float:left;
                  width:100%;
                  }

                  /*clientInfo*/

                #clientInfo{
                  float:left;
                  }
                /*#face img{
                    margin:2%;
                  float:left;
                  width:20%;
                  }*/

                #basicInfo{
                  margin: 1em 1em 0 1em;
                  float:left;
                  max-width:26em;
                  }
                #basicInfo h3{
                  font-size:1.5em;
                  margin: 0em 0em 0em 0.2em;
                  }
                .age{
                  font-size:0.8em;
                  font-weight:normal;

                  }
                #stage{
                  margin:0 0 0em 0em;
                  float:left;
                  }

                #stage p{
                  float:left;
                  color:#67a8bd;
                  font-size:0.8em;
                  letter-spacing:0em;
                  border-radius: 6px;
                  border:1px solid #67a8bd;
                  padding:0.4em 0.8em 0.4em 0.8em;
                  margin: 0.5em 0.5em 0 0;
                  }
                .contract{
                  clear:right;
                  color:#67a8bd;
                  padding-left:0.2em;
                  text-decoration:underline;
                  font-size:0.7em;
                  font-weight:100;
                  }
                #contantInfo{
                  margin:1em 0 1em 1em;
                  float:left;
                  line-height:1em;
                  font-size:1em;
                  }
                #contantInfo p{
                  float:left;
                  margin: 0em 0.5em 1em 0;
                  }
                .quez{
                  clear: left;
                  font-size: .8em;
                  width: 4em;
                  text-align: center;
                  border:1px solid #3C3C3C;
                  color: #3C3C3C;
                  border-radius: 4px;
                  padding: 0.2em;
                  }

                /*all forms*/

                  /* color line

                    .bBlueL{border:1px solid #b0cc;}
                      .blueL{border:1px solid #67a8bd;}
                        .pinkL{border-color:#e1c1c3;}
                          .greyL{border-color:#b1b3b6;}*/

                #formz{
                  font-size:1em;
                  clear:left;
                  width:100%;
                  opacity:0.8; /*ifFilled turn into 1.0*/
                  }
                  #formz li{
                      text-align:center;
                      width:45%;
                      float:left;
                      padding:2.5% 2.2% 3% 2.2%;
                      margin:0.2%;
                      border:1% solid #fff;
                      }
                    #formz a{


                        }

                      #formz a:hover{

                             font-weight:bolder;
                             }


      </style>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>


  <body>

    <!-- header -->
    <div id="header">
      <div id="logo">
        <a href="member_db.html" target="_self"><img src="/images/index-icon.png" alt=""/></a>
      </div>
      <p class="hello">Hello Penny Lin</p>
      <li class="viewAll"><a href="member_db.html" target="_self">18 client</a></li>
      <li class="tool"><a href="#" target="_self">Tool</a></li>
      <li class="add"><a href="#" target="_self">Add New</a></li>
    </div>
    <!-- searchbar -->
    <div id="search">
      <p>search</p>
    </div>


    <!-- clientInformation -->
    <div id="clientInfo">

      <!-- <div id="face">
        <img src="img/IMG_0699.jpg"  alt=""/>
        <div> -->
          <div id="basicInfo">
            <h3>Li Ting Wu <span class="age">34 </span><span class="contract">Under Contract</span></h3>



            <div id="stage">
              <p>Due:17/09/09 </p>
              <p>Singal Baby #2</p>
              <p>Homebirth</p>
              <p>Waterbirth</p>
              <p>Waterbirth</p>
            </div>
          </div>
          <div id="contantInfo">
            <p class="quez">Mobile</p> <p>0234 234 234  </p>
            <p class="quez">Phone</p> <p>02-2222 5222</p>
            <p class="quez">Address</p><p>21 Dartmouth St. 4108 Coopers Plains QLD</p>
            <p class="quez">Partner</p> <p>Adon Berwick 0888 88888 </p>
            <p class="quez">Mother</p> <p>Jane Fox 0888 88888 </p>

          </div>
          <!-- AllFormz -->
          <div id="formz">

            <!-- 產前 -->
            <li class="pregnancy"><a href="#" target="_self">初/複診照護表</a></li>
            <li class="pregnancy"><a href="#" target="_self">家庭社會功能評估</a></li>
            <li class="pregnancy"><a href="#" target="_self">產前憂鬱症評估</a></li>
            <li class="pregnancy"><a href="#" target="_self">資料保護同意書</a></li>
            <li class="pregnancy"><a href="#" target="_self">生產計劃</a></li>

            <!-- 產中 -->

            <li class="due"><a href="#" target="_self">諮詢紀錄表</a></li>

            <li class="due"><a href="#" target="_self">生產與分娩照護</a></li>

            <!-- 產後 -->
            <li class="pCare"><a href="#" target="_self">新生兒照護紀錄</a></li>
            <li class="pCare"><a href="#" target="_self">產後照護</a></li>
            <li class="pCare"><a href="#" target="_self">哺乳基本評估</a></li>
            <li class="pCare"><a href="#" target="_self">產後到府照護</a></li>
            <li class="pCare"><a href="#" target="_self">產後憂鬱症評估</a></li>

            <!-- 結案 -->
            <li class="closed"><a href="#" target="_self">產家與家屬申訴</a></li>
            <li class="closed"><a href="#" target="_self">滿意度調查</a></li>

          </div>

        </div>
        <!-- subNav -->
        <div id="subNav">

          <li ><a href="http://heqet.net/" title="About Heqet" target="_blank">About Heqet</a></li>
          <li><a href="http://heqet.net/contact" title="Contact Heqet" target="_blank">Contact</a></li>
          <li><a href="http://heqet.net/support" title="Contact Heqet" target="_blank">Support</a></li>

        </div>

        <!-- footer -->
        <div id="footer">
          <p>©2017 Heqet EHR.</p>
        </div>

  </body>
</html>

lib/hq_tw/web/templates/sample_page/dashboard.html.eex
<!doctype html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Welcome to Heqet</title>
    <style type="text/css">
      @charset "UTF-8";
      @import url('https://fonts.googleapis.com/css?family=Hind+Siliguri|Roboto+Slab');

      body{
        font-family: 'Hind Siliguri', serif;
        font-size:1em;
        color:#333;
        margin:0 auto;
        width:90%;
      }
      li{
        list-style:none;
        display:block;
        display:inline;

      }
      a{
        color: inherit;
        text-decoration:none;
      }
      /*font*/
      .hello{
        font-family: 'Hind Siliguri', sans-serif;
        color:#333;
        font-size:1.55em;
        font-weight:bold;
        letter-spacing:0em;
        margin:1.5em 0 2em 0em;
      }
      .info{
        font-size:1.5em;
      }
      /*color*/
      .pregnancy{background-color:#b0ccd9;
      }
      .due{background-color:#67a8bd;
      }
      .pCare{background-color:#e1c1c3;
      }
      .closed{background-color:#b1b3b6;
      }

      /*memberdb*/

      #logo img{
        float:left;
        margin:1.5em;
        width:4.1em;
      }
      #header{
        width:100%;
        float:left;
        margin-bottom:1em;

      }
      #header li {
        text-align:center;
        float:left;
        margin-bottom:1em;
        width:31.5%;
        margin: 0.5%;
      }

      .viewAll{
        color:#67a8bd;
        font-weight:normal;
        border:1px solid #67a8bd;
        border-radius: 40px;
      }

      .add{
        border-radius: 40px;
        color:#FFF;
        background-color:#67a8bd;
      }
      .tool{
        border-radius: 40px;
        color:#b1b3b6;
        border:1px solid #b1b3b6;
      }
      #search{
        text-align:center;
        clear:left;
        float:left;
        width:100%;
        border:1px solid #b1b3b6;;
        color:#b1b3b6;
        margin-bottom:1em;
        border-radius: 40px;
      }
      #clientz{
        width:100%;
        margin-bottom:1em;
      }
      #clientz li{
        float:left;
        color:#fff;
        width:30%;
        height:12em;
        margin:0.5%;
        padding: 0 0 0 2%;
      }


      #subNav{
        font-family:"Hind Siliguri", sans-serif;
        margin:1em 0em 0em 1em;
        width:100%;
        float:left;
      }

      #subNav li{
        color:#b1b3b6;
        float:left;
        width:31.5%;
        border-right:1px solid #b1b3b6;
        margin: 0.3%;
        font-size:14px;
        text-align:center;
      }
      #subNav a{
        color:#b1b3b6;
      }
      #subNav a:hover{
        color:#67a8bd;
        text-decoration:underline;
      }

      #footer{

        color:#b1b3b6;
        text-align:center;
        float:left;
        width:100%;
      }

      /*clientInfo*/

      #clientInfo{
        float:left;
      }
      /*#face img{
        margin:2%;
        float:left;
        width:20%;
      }*/

      #basicInfo{
        margin: 1em 1em 0 1em;
        float:left;
        max-width:26em;
      }
      #basicInfo h3{
        font-size:1.5em;
        margin: 0em 0em 0em 0.2em;
      }
      .age{
        font-size:0.8em;
        font-weight:normal;

      }
      #stage{
        margin:0 0 0em 0em;
        float:left;
      }

      #stage p{
        float:left;
        color:#67a8bd;
        font-size:0.8em;
        letter-spacing:0em;
        border-radius: 6px;
        border:1px solid #67a8bd;
        padding:0.4em 0.8em 0.4em 0.8em;
        margin: 0.5em 0.5em 0 0;
      }
      .contract{
        clear:right;
        color:#67a8bd;
        padding-left:0.2em;
        text-decoration:underline;
        font-size:0.7em;
        font-weight:100;
      }
      #contantInfo{
        margin:1em 0 1em 1em;
        float:left;
        line-height:1em;
        font-size:1em;
      }
      #contantInfo p{
        float:left;
        margin: 0em 0.5em 1em 0;
      }
      .quez{
        clear: left;
        font-size: .8em;
        width: 4em;
        text-align: center;
        border:1px solid #3C3C3C;
        color: #3C3C3C;
        border-radius: 4px;
        padding: 0.2em;
      }

      /*all forms*/

      /* color line

      .bBlueL{border:1px solid #b0cc;}
      .blueL{border:1px solid #67a8bd;}
      .pinkL{border-color:#e1c1c3;}
      .greyL{border-color:#b1b3b6;}*/

      #formz{
        font-size:1em;
        clear:left;
        width:100%;
        opacity:0.8; /*ifFilled turn into 1.0*/
      }
      #formz li{
        text-align:center;
        width:45%;
        float:left;
        padding:2.5% 2.2% 3% 2.2%;
        margin:0.2%;
        border:1% solid #fff;
      }
      #formz a{


      }

      #formz a:hover{

        font-weight:bolder;
      }

    </style>
  </head>

  <body>

    <div id="header">
      <div id="logo">
        <a href= <%= sample_page_path(@conn, :dashboard) %> target="_self"><img src="/images/index-icon.png" alt=""/></a>
      </div>
      <p class="hello">Hello Penny Lin</p>
      <li class="viewAll"><a href= <%= sample_page_path(@conn, :dashboard) %> target="_self">18 client</a></li>
      <li class="tool"><a href="#" target="_self">Tool</a></li>
      <li class="add"><a href="#" target="_self">Add New</a></li>
    </div>




    <!-- searchbar -->
    <div id="search"><p>search</p></div>
    <!-- clientoverview -->
    <div id="clientz">
      <li class="pregnancy" ><a href= <%= sample_page_path(@conn, :client) %>>
          <h3>Li Ting Wu</h3>
          <p>Due:17/09/09</p>
          <p>Pregnancy</p>
        </a></li>
        <li  class="due"><h3>Li Ting Wu</h3><p>Due:17/09/09</p><p>Due Soon</p></li>
        <li  class="pCare"><h3>Li Ting Wu</h3><p>Born:17/09/09</p><p>Postnatal Care</p></li>
        <li  class="closed"><h3>Li Ting Wu</h3><p>CC:17/09/09</p><p>Case Closed</p></li>
    </div>
    <!-- subNav -->
    <div id="subNav">
      <li ><a href="http://heqet.net/" title="About Heqet" target="_blank">About Heqet</a></li>
      <li><a href="http://heqet.net/contact" title="Contact Heqet" target="_blank">Contact</a></li>
      <li><a href="http://heqet.net/support" title="Contact Heqet" target="_blank">Support</a></li>
    </div>
    <!-- footer -->
    <div id="footer">
      <p>©2017 Heqet EHR.</p>
    </div>


  </body>
</html>

lib/hq_tw/web/templates/sample_page/login.html.eex
<!doctype html>
<html>
  <head>
    <meta charset="UTF-8">

    <title>Welcome to Heqet login</title>

    <style type="text/css" link href="https://fonts.googleapis.com/css?family=Hind+Siliguri|Roboto+Slab" rel="stylesheet">
      body{
        height:70%;
        font-family: "Hind Siliguri", sans-serif;
        text-align:center;
        padding-top: 13vh;


      }

      a{
        text-decoration:none;
        color:#67a8bd;
      }

      p{
        font-size:14px;
        color:#333333;
      }

      #logo{

      }

      #logo heqet{
        font-family: "Roboto Slab", serif;
        font-weight:300;
        font-size: 52px;
        color: #333;
        text-transform: uppercase;
        letter-spacing: 18px;
      }

      #logo p{
        font-size:14px;

        color:#333;
        letter-spacing: 1px;
        margin: 5px 6px 0px 0px;
      }
      #logo img{
        size:100%;
      }

      #loginForm{
        margin: 20px 0px 0px 0px;
      }
      #loginForm input{
        font-size:1em;
        border:1px thin #333;
        background-color:#FFF;
        border-radius: 1em;
        height:1.8em;
        width:18em;
        text-align:center;
        letter-spacing:0.1em;
      }
      input#submit{
        color:#FFF;
        font-size:1em;
        margin:1em;
        background-color:#67a8bd;
        border:0px soild #67a8bdF;
        border-radius: 1em;
      }

      #loginForm a:hover{
        font-weight:bold;

      }
    </style>
  </head>

  <body>
    <div id="logo">
      <img src="/images/logo_header.png" /><br/>
      <heqet>heqet</heqet><br/>
      <p>Electronic Health Record</p>
    </div>


    <div id="loginForm">
      <form action="img/http/heqet.net/login.php" >
        <p class="input"><input type="text" name="username"  placeholder="Username">
        </p>

        <p> <input type="password" name="password" placeholder="Password">
        </p>
        <P> <input type="submit" value="Login" id="submit"></P>

      </form>
    </div>

    <div id="loginFail">
      <p>Can not login? Click <a href=<%= sample_page_path(@conn, :dashboard) %> target="_self">here.</a></p>
    </div>

  </body>
</html>